spring.application.name=ChatBotWithAi

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=mixtral-8x7b-32768
spring.ai.openai.embedding.enabled=false

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB