spring.application.name=ChatBotWithAi

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=llama-3.1-8b-instant

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB