spring.application.name=ChatBotWithAi

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=openai/gpt-oss-20b

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB